### ISSUE TITLE
Proposal: restructure configuration file

### ISSUE THREAD

**Issue by salimane** [pivotal/LicenseFinder#128]
I love the recent work on version 2.0.0.

With the version 2.0.0, we now have 2 configurations files: 
*  ``config/license_finder.yml`` 
*  ``dependency_decisions.yml`` 

``config/license_finder.yml`` stores the location of ``dependency_decisions.yml``, ``dependency_decisions.yml`` stores any decisions you make about approvals.

I think we can combine both files by just using ``config/license_finder.yml`` and making it human writable/computer readable.

The only reason we setup  ``dependency_decisions.yml`` is because we want to run commands like : 
```license_finder approval add awesome_gpl_gem --who CTO --why "Go ahead"``` 

and let ``license_finder`` writes the decision for us in ``dependency_decisions.yml``. But we might as well write directly the decision in ``config/license_finder.yml`` if we are writing the same thing on the command line.

In order to achieve that, I'm proposing to the following structure for ``config/license_finder.yml``:
```yaml
default_approval: &default_approval
  who: WHO
  why: Reason
  when: 2014-12-30

project_name: MyProject
gradle_command: # only meaningful if used with a Java/gradle project. Defaults to "gradle".
whitelist:
  'MIT':
    <<: *default_approval
  'ISC':
    <<: *default_approval
    include:
      rake:
        <<: *default_approval
      json:
        who: MY_WHO
        why: MY_REASON
        when: 2014-12-30
  'LGPL':
    <<: *default_approval
  'LAGPL':
    who: ANOTHER_WHO
    why: ANOTHER_REASON
    when: 2014-12-30
ignore_groups:
  test:
    <<: *default_approval
  development:
    who: AND_ANOTHER_WHO
    why: AND_ANOTHER_REASON
    when: 2014-12-30
ignore_dependencies:
  bundler:
    <<: *default_approval
  another_gem:
    who: ANOTHER_WHO
    why: ANOTHER_REASON
    when: 2014-12-30

```

With the above:
* New approval can be added manually and easily
* We can read this easily in ruby
* We get rid of ``dependencies_file_dir``
* We only have configuration file ``config/license_finder.yml``
* We don't need command lines like ``license_finder approval``, ``license_finder dependencies``, ``license_finder whitelist``, ``license_finder licenses``...
* We can then cleanup all the dead codes related to the command lines

@mainej what do you think ?

Thanks

**Comment by salimane** [comment]
On my fork ``salimane/LicenseFinder``, branch ``config``, I've already got a working version with the following:
* one configuration file `config/license_finder.yml`
  (deprecation of `doc/dependency_decisions.yml`)
* configuration file structure overhaul with the one proposed here
* deprecation of subcommands `approvals`, `approvals`,
  `dependencies`, `ignored_dependencies`, `ignored_groups`, `licenses`,
  `project_name`, `whitelist`. We can now directly edit the config file
* readme updated to reflect the code changes
* everything is working as before

The remaining work is basically to clean up the spec and reflect the new structure in the tests. 

Please, try that branch locally and send some feedback.

Thanks

**Comment by beryllium** [comment]
Might be outside the scope of this issue, but would it be possible to pass the configuration file (`config/license_finder.yml`) as a parameter to the license_finder command? I need to locate it within a non-standard hierarchy for one of my projects.

**Comment by mainej** [comment]
@beryllium split your proposal into a separate issue: #131.  It's somewhat related, but this proposal already has a bit too much going on in it.

@salimane I'll make separate comments about your `config` branch when I have a chance to look it over.

**Comment by salimane** [comment]
@mainej I understand what you mean. As you described above, that's how the current code is structured. But to support the above functionality, I could do this instead in my branch:

```yaml
approvals:
  rb-fchange:
    <<: *default_approval
    license:
      name: GPL
      <<: *default_approval
  json:
    version: 1.2.1
    <<: *default_approval
```

In essence, merging the meaning of ``licenses``, ``packages``, ``approvals`` and removing all the current ``include``.

The user would just enter that in the yaml file. Internally, I'll populate the related object accordingly if I find  a license or not. This would fix your point 1 and 2.

By the way, theoretically, specifying an "hidden package" dependency is already duplicating ``approvals`` and ``licences`` (if there is a license specified). Forward, to make simple, a "hidden package" and a "known package" would just be  the same. 

Does this solve your concerns ?

Thanks

**Comment by mainej** [comment]
> Does this solve your concerns ?

Not really, or at least not for my work as a consultant.  With my clients there is often a long period between when I know about a dependency (and its licenses) and when I actually get approval.  For me, that is a large part of the reason for `license_finder`.  I want to gather as much information as I can and store it somewhere, so that in 3 weeks I will have a reminder that the client and/or their lawyers _still_ haven't gotten me an approval, and that I need to prompt them again.  Based on your designs (for "whitelist" and "approvals") it looks like in your work dependencies don't need to be documented until they are approved.  For me, it is the opposite... it's most useful to document them before they are approved.  Once they are approved, I can forget about them and focus instead on tracking the ones that haven't been approved.

**Comment by salimane** [comment]
@mainej hmm... I would try to make it work for both of us :)
So to fulfil your wishes to document things as a consultant before they are approved, I'm proposing this structure:

```yaml
default_approval: &default_approval
  who: 'WHO'
  why: 'REASON'
  when: 2015-01-01

project_name: ProjectName
gradle_command: # only meaningful if used with a Java/gradle project. Defaults to "gradle".
whitelist:
  'BSD':
    <<: *default_approval
  'MIT':
    <<: *default_approval
packages:
  rb-fchange:
    approved: true
    when: 2014.01.01
    license:
      name: GPL
      <<: *default_approval
  rake:
    when: '2012.01.01'
    license:
      name: GPL
  json:
    approved: true
    version: 1.2.1
    <<: *default_approval
  csshack:
    version: 1.2.1
    when: 2011.01.01
ignore_groups:
  development:
    <<: *default_approval
ignore_dependencies:
  xpath:
    <<: *default_approval
    when: 2015-01-02

```

With the above:
*  ``rb-fchange`` has been approved with ``GPL`` license
*  ``rake`` has been documented with  ``GPL`` license but still waiting for approval since ``2012.01.01``
*  ``json`` has been approved but with no license
*  ``rack`` has been documented with no license but still waiting for approval since ``2011.01.01``

I think this should solve everyone's problems while still be human writable, simple to read, represent the current state of affairs, DRY, one config file....unless what you were looking for is an audit log.

What do you think @mainej ? :smile: 

Thanks
