### ISSUE TITLE
Proposal: parameterize the location of the config file

### ISSUE THREAD

**Issue by mainej** [pivotal/LicenseFinder#131]
Pro: could put config file in a non-standard part of the hierarchy.

Con: It seems silly to parameterize both the `--decision_file` and the `--config_file`, when one of the main jobs of the config file is to set the location of the decision file.

Work-around: in version 2, the only things `config/license_finder.yml` has in it are `decision_file` and `gradle_command`, both of which can be provided as CLI parameters... That is, the config file doesn't NEED to exist if you remember to pass those parameters to all commands which accept them.

Notes: Maybe this is another indication we should merge the config file and decision file (cc @salimane).  A first pass might be:
1. Merge the config file and the decisions file; something like:
```yaml
---
gradle_command: gradlew
project_name: myproj # it's a bit strange to have this in decisions
decisions: [...]
```
2. Make --config_file parameterizable, with a default of `config/license_finder.yml` or even `./license_finder.yml`, because not all projects have a `config` directory.
