### ISSUE TITLE
GPL gem reported as MIT

### ISSUE THREAD

**Issue by thbar** [pivotal/LicenseFinder#205]
I did a quick test (since I'm just discovering LicenseFinder) and built a Gemfile which includes [roo-xls](https://github.com/roo-rb/roo-xls), itself depending on the [spreadsheet](https://rubygems.org/gems/spreadsheet) gem (GPLV3).

The spreadsheet gem is incorrectly reported as MIT. I investigated very quickly:
* The [gemspec](https://github.com/zdavatz/spreadsheet/blob/master/spreadsheet.gemspec) mentions indeed GPLv3.
* The [license.txt](https://github.com/zdavatz/spreadsheet/blob/master/LICENSE.txt) also mentions GPLv3.
* After digging a bit, [rubygems](https://rubygems.org/gems/spreadsheet) reports MIT.

So my first guess is that LicenseFinder delegates the finding to bundler, which relies on rubygems.org, which seems to have incorrect data.

I wonder: should LicenseFinder itself use multiple sources for data cleaning and coherence checking, in order to be truly trustable? What can be done to improve data quality here? Etc.

**Comment by franckverrot** [comment]
The `metadata` file in the `spreadsheet` gem is actually reporting `MIT` as its license. 

I did a quick investigation and the `MIT` license only appeared in the version 1.0.2 of the gem. The only change I can notice is that the version of Rubygems that has been used for 1.0.2 is different from the one used for 1.0.2: Rubygems has been updated from v2.3.0 to v2.4.5. So I'm not sure what happens here...

**Comment by shaneog** [comment]
To add to this I've just discovered another gem which is reported as MIT but seems to actually be GPL. The gem is [ruby-graphviz](https://github.com/glejeune/Ruby-Graphviz), and although the README references MIT it's just for an included component, the gem itself seems to be GPL licensed.
[Rubygems](https://rubygems.org/gems/ruby-graphviz) reports N/A.

**Comment by flavorjones** [comment]
LicenseFinder defaults to using what's present in the gem's gemspec.

For roo-xls, the gemspec declares MIT: https://github.com/roo-rb/roo-xls/blob/master/roo-xls.gemspec#L14

Please open an issue with the roo-xls project asking them to correct their gemspec to reflect the appropriate license.

For ruby-graphviz, the gemspec does not declare a license (which is why Rubygems shows "N/A"), and there is no LICENSE or LICENSE.txt file declaring the canonical license, and so LicenseFinder falls back to looking for matching text in the README, and so finds the MIT license declared for `nothugly.xsl`.

Please open an issue with the ruby-graphviz project asking them to declare a license in their gemspec.

**Comment by thbar** [comment]
@flavorjones there is a misunderstanding - the bogus license report is not on roo-xls but rather on spreadsheet (a roo-xls dependency), which has a `GPLv3` license in its [gemspec](https://github.com/zdavatz/spreadsheet/blob/master/spreadsheet.gemspec#L14) but was reported as MIT by LicenseFinder, at the time where I did those tests.

I'm not using LicenseFinder anymore (after finding this problem), but I think the original bug report still applies and would require investigation.

**Comment by flavorjones** [comment]
@thbar spreadsheet 1.1.2 declares MIT in the gemspec distributed with the gem. You can unpack the gem yourself and investigate if you like. It looks like the gemspec in their source repo declares GPLv3, so I'm not sure how that change didn't propagate into the published gem.

Please open an issue with the spreadsheet project asking them to properly release a gem with the appropriate license declared in the gemspec.

**Comment by thbar** [comment]
@flavorjones I just checked - it looks like if I install the gem (v1.1.2) and unpack it, its gemspec mentions GPLv3 (like on the Github repo - but unlike on the [spreadsheet rubygems page](https://rubygems.org/gems/spreadsheet)):

```
$ gem install spreadsheet
Fetching: ruby-ole-1.2.12.gem (100%)
Successfully installed ruby-ole-1.2.12
Fetching: spreadsheet-1.1.2.gem (100%)
Successfully installed spreadsheet-1.1.2
2 gems installed
gem unpack spreadsheet
Unpacked gem: '/Users/thbar/spreadsheet-1.1.2'
$ cd spreadsheet-1.1.2
cat spreadsheet.gemspec | grep license
   s.license     = "GPLv3"
```

Something is going on here!

**Comment by flavorjones** [comment]
Not when I unpack it:

```
--- !ruby/object:Gem::Specification
name: spreadsheet
version: !ruby/object:Gem::Version
  version: 1.1.2
platform: ruby
authors:
- Masaomi Hatakeyama, Zeno R.R. Davatz
autorequire:
bindir: bin
cert_chain: []
date: 2016-03-29 00:00:00.000000000 Z
dependencies:
- !ruby/object:Gem::Dependency
  name: ruby-ole
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '1.0'
  type: :runtime
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - ">="
      - !ruby/object:Gem::Version
        version: '1.0'
- !ruby/object:Gem::Dependency
  name: rdoc
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '4.0'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '4.0'
- !ruby/object:Gem::Dependency
  name: hoe
  requirement: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '3.7'
  type: :development
  prerelease: false
  version_requirements: !ruby/object:Gem::Requirement
    requirements:
    - - "~>"
      - !ruby/object:Gem::Version
        version: '3.7'
description: |-
  The Spreadsheet Library is designed to read and write Spreadsheet
Documents.
  As of version 0.6.0, only Microsoft Excel compatible spreadsheets are
  supported. Spreadsheet is a combination/complete rewrite of the
  Spreadsheet::Excel Library by Daniel J. Berger and the ParseExcel Library
by
  Hannes Wyss. Spreadsheet can read, write and modify Spreadsheet Documents.
email:
- mhatakeyama@ywesee.com, zdavatz@ywesee.com
executables:
- xlsopcodes
extensions: []
extra_rdoc_files:
- GUIDE.md
- History.md
- LICENSE.txt
- Manifest.txt
- README.md
files:
- ".gemtest"
- ".gitignore"
- ".travis.yml"
- Excel97-2007BinaryFileFormatSpecification.pdf
- GUIDE.md
- Gemfile
- Gemfile.lock
- History.md
- LICENSE.txt
- Manifest.txt
- README.md
- Rakefile
- bin/xlsopcodes
- excelfileformat.pdf
- lib/parseexcel.rb
- lib/parseexcel/parseexcel.rb
- lib/parseexcel/parser.rb
- lib/spreadsheet.rb
- lib/spreadsheet/column.rb
- lib/spreadsheet/compatibility.rb
- lib/spreadsheet/datatypes.rb
- lib/spreadsheet/encodings.rb
- lib/spreadsheet/errors.rb
- lib/spreadsheet/excel.rb
- lib/spreadsheet/excel/error.rb
- lib/spreadsheet/excel/internals.rb
- lib/spreadsheet/excel/internals/biff5.rb
- lib/spreadsheet/excel/internals/biff8.rb
- lib/spreadsheet/excel/offset.rb
- lib/spreadsheet/excel/password_hash.rb
- lib/spreadsheet/excel/reader.rb
- lib/spreadsheet/excel/reader/biff5.rb
- lib/spreadsheet/excel/reader/biff8.rb
- lib/spreadsheet/excel/rgb.rb
- lib/spreadsheet/excel/row.rb
- lib/spreadsheet/excel/sst_entry.rb
- lib/spreadsheet/excel/workbook.rb
- lib/spreadsheet/excel/worksheet.rb
- lib/spreadsheet/excel/writer.rb
- lib/spreadsheet/excel/writer/biff8.rb
- lib/spreadsheet/excel/writer/format.rb
- lib/spreadsheet/excel/writer/n_worksheet.rb
- lib/spreadsheet/excel/writer/workbook.rb
- lib/spreadsheet/excel/writer/worksheet.rb
- lib/spreadsheet/font.rb
- lib/spreadsheet/format.rb
- lib/spreadsheet/formula.rb
- lib/spreadsheet/helpers.rb
- lib/spreadsheet/link.rb
- lib/spreadsheet/note.rb
- lib/spreadsheet/noteObject.rb
- lib/spreadsheet/row.rb
- lib/spreadsheet/workbook.rb
- lib/spreadsheet/worksheet.rb
- lib/spreadsheet/writer.rb
- spreadsheet.gemspec
- test/data/test_adding_data_to_existing_file.xls
- test/data/test_borders.xls
- test/data/test_changes.xls
- test/data/test_comment.xls
- test/data/test_copy.xls
- test/data/test_datetime.xls
- test/data/test_empty.xls
- test/data/test_formula.xls
- test/data/test_long_sst_record.xls
- test/data/test_margin.xls
- test/data/test_merged_and_protected.xls
- test/data/test_merged_cells.xls
- test/data/test_missing_row.xls
- test/data/test_pagesetup.xls
- test/data/test_text_drawing.xls
- test/data/test_version_excel5.xls
- test/data/test_version_excel95.xls
- test/data/test_version_excel97.xls
- test/data/test_version_excel97_2010.xls
- test/data/test_worksheet_visibility.xls
- test/excel/reader.rb
- test/excel/row.rb
- test/excel/writer/workbook.rb
- test/excel/writer/worksheet.rb
- test/font.rb
- test/format.rb
- test/integration.rb
- test/row.rb
- test/suite.rb
- test/workbook.rb
- test/workbook_protection.rb
- test/worksheet.rb
homepage:
licenses:
- MIT
metadata: {}
post_install_message:
rdoc_options:
- "--main"
- README.md
require_paths:
- lib
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '0'
required_rubygems_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '0'
requirements: []
rubyforge_project: spreadsheet
rubygems_version: 2.4.5
signing_key:
specification_version: 4
summary: The Spreadsheet Library is designed to read and write Spreadsheet
Documents
test_files: []
```

the key bit being:

```
licenses:
- MIT
```
