### ISSUE TITLE
BUNDLE_GEMFILE location isn't respected

### ISSUE THREAD

**Issue by nbibler** [pivotal/LicenseFinder#508]
Bundler has support for using a `BUNDLE_GEMFILE` environment variable (as well as passing a `--gemfile` to various tasks) to set the path to the Gemfile to use. Bundler does not require that a Gemfile be named `Gemfile` nor that it exist in the current directory.

license_finder appears to assume that it always uses a `Gemfile` in the current directory and ignores any `BUNDLE_GEMFILE` environment configuration.

This issue often comes up for me when using something like [Appraisal](https://rubygems.org/gems/appraisal) and running in a CI environment like Travis CI.

**Comment by nbibler** [comment]
For anyone else with a similar problem, this is a snippet of what I've recently been putting into my `.travis.yml` configuration files for running license_finder with appraisal. This removes the root `Gemfile` and `Gemfile.lock` and replaces it with the appraisal-generated files for the currently-running test matrix:

```yaml
before_script:
  - cp $BUNDLE_GEMFILE ./Gemfile
  - cp $BUNDLE_GEMFILE.lock ./Gemfile.lock
  - "sed -ie 's#gemspec path: \"../\"#gemspec#' Gemfile"
  - "sed -ie 's/remote: \\.\\./remote: ./' Gemfile.lock"
script:
  - bundle exec license_finder --quiet
```
