### ISSUE TITLE
[Decision inheritance] - Get the decisions file from a private URL 

### ISSUE THREAD

**Issue by ricardoperez** [pivotal/LicenseFinder#751]
Hi, 

I'm try to use `decision_inheritance` new feature with a "decisions" file hosted in a private git repo. The only problem I'm facing, there is no way to set `Authorization` header with token to get the file.

Would be nice to have in the  `inherit_from` decision, a way to set a Bearer token, like:

```yml
- - :inherit_from
  - url: https://raw.githubusercontent.com/repo-with-config/master/doc/dependency_decisions.yml
    token: BEARER_TOKEN
```

Releated: #735
