### ISSUE TITLE
Flutter pub license detection results in unknown license for package added from GitHub

### ISSUE THREAD

**Issue by jtruenary** [pivotal/LicenseFinder#920]
When I run license finder in a flutter project, it results in unknown license for packages added from GitHub, even though they have proper license.

I have also properly set PUB_CACHE environment variable.

**Environment** 

License Finder : 7.0.1
Flutter Version: 3.0.1

Example PubSpec Configuration:

```
dependencies: 
  charts_flutter:
     git:
      url: https://github.com/jamesblasco/charts/
      path: charts_flutter
      ref: dev
```
